import {useEffect,useState} from 'react';
import {createAnalysis,getAnalysisResults,getAnalysisStatus,getWorkflowDetails} from './api';
const initialForm={patient_id:'PATIENT-105',tumor_sample_id:'TUMOR',normal_sample_id:'NORMAL',tumor_file:'/app/input/reads/tumor.fastq',normal_file:'/app/input/reads/normal.fastq',reference_fasta:'/app/input/reference/toy_reference.fa',reference_genome:'ToyGenome-v1'};
export default function App(){
 const [form,setForm]=useState(initialForm),[analysisId,setAnalysisId]=useState(null),[status,setStatus]=useState(null),[results,setResults]=useState([]),[workflow,setWorkflow]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(!analysisId)return;let timer;const poll=async()=>{try{const s=await getAnalysisStatus(analysisId);setStatus(s);if(s.status==='COMPLETED'){setResults(await getAnalysisResults(analysisId));setWorkflow(await getWorkflowDetails(analysisId));clearInterval(timer)}else if(s.status==='FAILED'){setWorkflow(await getWorkflowDetails(analysisId));setError(s.error_message||'Analysis failed');clearInterval(timer)}}catch(e){setError(e.response?.data?.detail||e.message);clearInterval(timer)}};poll();timer=setInterval(poll,1500);return()=>clearInterval(timer)},[analysisId]);
 const submit=async e=>{e.preventDefault();setError('');setResults([]);setWorkflow(null);const a=await createAnalysis(form);setAnalysisId(a.analysis_id);setStatus(a)};
 return <main className="page"><section className="hero"><p className="eyebrow">Real Nextflow variant calling MVP</p><h1>Genomics Variant Calling Platform</h1><p>React submits tumor-normal FASTQ files. Nextflow runs BWA, SAMtools and BCFtools and returns VCF-derived variants.</p></section><section className="card"><h2>Start variant calling</h2><form onSubmit={submit} className="form-grid">{Object.entries(form).map(([k,v])=><label key={k}>{k.replaceAll('_',' ')}<input value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button>Start Nextflow Variant Calling</button></form>{error&&<p className="error">{error}</p>}</section>{status&&<section className="card"><h2>Analysis {analysisId}</h2><p><b>{status.status}</b> · {status.current_step}</p><p>Engine: {status.workflow_engine||'Nextflow'} · Pipeline: {status.pipeline_name||'variant_calling.nf'} · Version: {status.nextflow_version||'pending'}</p><div className="progress-track"><div className="progress-fill" style={{width:`${status.progress}%`}}/></div></section>}{workflow&&<section className="card"><h2>Workflow execution</h2><p>Run: {workflow.nextflow_run_name}</p><table><thead><tr><th>Process</th><th>Status</th><th>Exit</th><th>Duration</th></tr></thead><tbody>{workflow.processes.map((p,i)=><tr key={i}><td>{p.process}</td><td>{p.status}</td><td>{p.exit_code}</td><td>{p.duration}</td></tr>)}</tbody></table></section>}{results.length>0&&<section className="card"><h2>Called variants</h2><table><thead><tr><th>Sample</th><th>Chr</th><th>Pos</th><th>Ref</th><th>Alt</th><th>GT</th><th>QUAL</th></tr></thead><tbody>{results.map((r,i)=><tr key={i}><td>{r.sample}</td><td>{r.chromosome}</td><td>{r.position}</td><td>{r.reference}</td><td>{r.alternate}</td><td>{r.genotype}</td><td>{r.quality}</td></tr>)}</tbody></table></section>}</main>
}
